name: appcraft_utils_flutter
version: 0.0.1
repository: https://github.com/AppCraftTeam/appcraft-utils-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
